name: Build Fungify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Backend Build (Spring Boot)
    - name: Setup Java environment
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        
    - name: Check directory structure
      run: |
        ls -la
        find . -name "mvnw" -type f
        
    - name: Build Spring Boot app
      working-directory: ./Backend
      run: |
        chmod +x ./mvnw
        ./mvnw clean package
      continue-on-error: true  # Bu adımın başarısız olması durumunda devam etmek için

    # Mobile Build (Flutter)
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'
        
    - name: Change to Mobile App directory
      run: cd "./Mobile App" || echo "Directory not found"
      
    - name: Get Flutter dependencies
      working-directory: "./Mobile App"
      run: flutter pub get
      continue-on-error: true  # Bu adımın başarısız olması durumunda devam etmek için
      
    - name: Build APK (Release)
      working-directory: "./Mobile App"
      run: flutter build apk --release
      continue-on-error: true  # Bu adımın başarısız olması durumunda devam etmek için

    # Upload Artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Fungify-Builds
        path: |
          Backend/target/*.jar
          Mobile App/build/app/outputs/flutter-apk/*.apk
        if-no-files-found: warn  # Dosya bulunamazsa uyarı ver ama hata değil
  
  